language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
  - "pypy3"
env:
  - DJANGO_VERSION="Django<1.9"
  - DJANGO_VERSION="Django<1.8"
  - DJANGO_VERSION="Django<1.7"
  - DJANGO_VERSION="Django<1.6"
  - DJANGO_VERSION="Django<1.9" RIPOZO="git+git://github.com/vertical-knowledge/ripozo.git@master"
install:
  - pip install coveralls
  - pip install --pre $DJANGO_VERSION
  - python setup.py -q install
script:
  coverage run --source=django_ripozo setup.py test
after_success:
  coveralls