language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
  - "pypy3"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.5.12
install:
  - pip install coveralls
  - pip install -U ripozo-tests
  - pip install --pre Django==$DJANGO_VERSION
  - python setup.py -q install
script:
  coverage run --source=django_ripozo setup.py test
after_success:
  coveralls